### PR TITLE
logging update

### PR DESCRIPTION
**Pull request by toanju**
* use of `__FUNCTION__` instead of `__PRETTY_FUNCTION__` is sufficient
* add missing `__FUNCTION__` logs

### CODE REVIEW

**Comment by DFritzsche** [comment]
please check commit msg

**Comment by toanju** [comment]
sorry, can't see what you are thinking. can you be more precise?

**Comment by DFritzsche** [comment]
this does not make sense to me:

> use of __FUNCTION__ instead of __PRETTY_FUNCTION__ is sufficientuse of __FUNCTION__ instead of __PRETTY_FUNCTION__ is sufficient

**Comment by toanju** [comment]
thanks!

**Pull request merged**
